// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpz8eS_EPrgnXcftwkNYjfLShBqj-N7M',
    appId: '1:129528742325:web:83bcbeea8c46893671d9fc',
    messagingSenderId: '129528742325',
    projectId: 'digital-wallet-and-tracker',
    authDomain: 'digital-wallet-and-tracker.firebaseapp.com',
    storageBucket: 'digital-wallet-and-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpz8eS_EPrgnXcftwkNYjfLShBqj-N7M',
    appId: '1:129528742325:android:f8ec052d75717ecd71d9fc',
    messagingSenderId: '129528742325',
    projectId: 'digital-wallet-and-tracker',
    storageBucket: 'digital-wallet-and-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSpz8eS_EPrgnXcftwkNYjfLShBqj-N7M',
    appId: '1:129528742325:ios:some_placeholder_id',
    messagingSenderId: '129528742325',
    projectId: 'digital-wallet-and-tracker',
    storageBucket: 'digital-wallet-and-tracker.firebasestorage.app',
    iosBundleId: 'com.example.walletG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSpz8eS_EPrgnXcftwkNYjfLShBqj-N7M',
    appId: '1:129528742325:ios:some_placeholder_id',
    messagingSenderId: '129528742325',
    projectId: 'digital-wallet-and-tracker',
    storageBucket: 'digital-wallet-and-tracker.firebasestorage.app',
    iosBundleId: 'com.example.walletG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSpz8eS_EPrgnXcftwkNYjfLShBqj-N7M',
    appId: '1:129528742325:web:83bcbeea8c46893671d9fc',
    messagingSenderId: '129528742325',
    projectId: 'digital-wallet-and-tracker',
    authDomain: 'digital-wallet-and-tracker.firebaseapp.com',
    storageBucket: 'digital-wallet-and-tracker.firebasestorage.app',
  );
}
