// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAia0Uh93oARvOcxGDjHqwn7nkS9HLjdqk',
    appId: '1:676404499217:web:1a07dfef6eaa0bf421f2b0',
    messagingSenderId: '676404499217',
    projectId: 'ai-wallet-ecc12',
    authDomain: 'ai-wallet-ecc12.firebaseapp.com',
    storageBucket: 'ai-wallet-ecc12.firebasestorage.app',
    measurementId: 'G-2QV4GHED71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwv2ftwsiHN2iuUnba7NPhhobyDLlhn7M',
    appId: '1:676404499217:android:4b120666d30d247521f2b0',
    messagingSenderId: '676404499217',
    projectId: 'ai-wallet-ecc12',
    storageBucket: 'ai-wallet-ecc12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MNDpRzcveAeM7vBbmAMDmUQyaLm--40',
    appId: '1:676404499217:ios:5bff4afca93a27d821f2b0',
    messagingSenderId: '676404499217',
    projectId: 'ai-wallet-ecc12',
    storageBucket: 'ai-wallet-ecc12.firebasestorage.app',
    iosBundleId: 'com.example.walletg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MNDpRzcveAeM7vBbmAMDmUQyaLm--40',
    appId: '1:676404499217:ios:5bff4afca93a27d821f2b0',
    messagingSenderId: '676404499217',
    projectId: 'ai-wallet-ecc12',
    storageBucket: 'ai-wallet-ecc12.firebasestorage.app',
    iosBundleId: 'com.example.walletg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAia0Uh93oARvOcxGDjHqwn7nkS9HLjdqk',
    appId: '1:676404499217:web:5a4050cf5764c7c721f2b0',
    messagingSenderId: '676404499217',
    projectId: 'ai-wallet-ecc12',
    authDomain: 'ai-wallet-ecc12.firebaseapp.com',
    storageBucket: 'ai-wallet-ecc12.firebasestorage.app',
    measurementId: 'G-S5W2SGF0RT',
  );
}
