// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0OARFGE9PgpWvfvsE4fQAXgeUkoCx9Q',
    appId: '1:947462306422:web:d78de97bfb5ffc80183d57',
    messagingSenderId: '947462306422',
    projectId: 'digital-wallet-new',
    authDomain: 'digital-wallet-new.firebaseapp.com',
    storageBucket: 'digital-wallet-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-BOnhLrllg3-OdMHagDFmD956pvZ8_g',
    appId: '1:947462306422:android:c65fff8aaeb1bfad183d57',
    messagingSenderId: '947462306422',
    projectId: 'digital-wallet-new',
    storageBucket: 'digital-wallet-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0n3h02HUL2gRvAHUuevJxHjY-j0Um-SA',
    appId: '1:947462306422:ios:c864ac8927b94d8d183d57',
    messagingSenderId: '947462306422',
    projectId: 'digital-wallet-new',
    storageBucket: 'digital-wallet-new.firebasestorage.app',
    iosBundleId: 'com.example.walletg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0n3h02HUL2gRvAHUuevJxHjY-j0Um-SA',
    appId: '1:947462306422:ios:c864ac8927b94d8d183d57',
    messagingSenderId: '947462306422',
    projectId: 'digital-wallet-new',
    storageBucket: 'digital-wallet-new.firebasestorage.app',
    iosBundleId: 'com.example.walletg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO0OARFGE9PgpWvfvsE4fQAXgeUkoCx9Q',
    appId: '1:947462306422:web:bbdf1b60e93a18f0183d57',
    messagingSenderId: '947462306422',
    projectId: 'digital-wallet-new',
    authDomain: 'digital-wallet-new.firebaseapp.com',
    storageBucket: 'digital-wallet-new.firebasestorage.app',
  );

}
