import 'locale_manager.dart';

class L10n {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'my_money': 'My Money',
      'payment_settings': 'Payment Settings',
      'app_settings': 'App Settings',
      'more': 'More',
      'language': 'Language',
      'theme': 'Theme',
      'notifications': 'Notifications',
      'privacy_security': 'Privacy & Security',
      'help_support': 'Help & Support',
      'about': 'About',
      'logout': 'Logout',
      'bank_accounts': 'Bank Accounts',
      'my_cards': 'My Cards',
      'personal_info': 'Personal Info',
      'select_language': 'Select Language',
      'language_set_to': 'Language set to',
      'home': 'Home',
      'insights': 'Insights',
      'history': 'History',
      'transfer_money': 'Transfer Money',
      'to_contact': 'To Contact',
      'to_bank': 'To Bank/UPI ID',
      'to_self': 'To Self Account',
      'check_balance': 'Check Balance',
      'recharge_pay_bills': 'Recharge & Pay Bills',
      'recent_transactions': 'Recent Transactions',
      'to_mobile': 'To Mobile',
      'people': 'People',
      'view_all': 'View All',
      'setup': 'Setup',
      'offers_rewards': 'Offers & Rewards',
      'autopay_management': 'Autopay Management',
      'chatbot': 'Expensya',
    },
    'hi': {
      'my_money': 'मेरा पैसा',
      'payment_settings': 'भुगतान सेटिंग्स',
      'app_settings': 'ऐप सेटिंग्स',
      'more': 'अधिक',
      'language': 'भाषा',
      'theme': 'थीम',
      'notifications': 'सूचनाएं',
      'privacy_security': 'गोपनीयता और सुरक्षा',
      'help_support': 'सहायता और समर्थन',
      'about': 'बारे में',
      'logout': 'लॉग आउट',
      'bank_accounts': 'बैंक खाते',
      'my_cards': 'मेरे कार्ड',
      'personal_info': 'व्यक्तिगत जानकारी',
      'select_language': 'भाषा चुनें',
      'language_set_to': 'भाषा बदल दी गई है: ',
      'home': 'होम',
      'insights': 'इनसाइट्स',
      'history': 'इतिहास',
      'transfer_money': 'पैसे ट्रांसफर करें',
      'to_contact': 'संपर्क को',
      'to_bank': 'बैंक/यूपीआई',
      'to_self': 'स्वयं को',
      'check_balance': 'बैलेंस चेक',
      'recharge_pay_bills': 'रिचार्ज और बिल',
      'recent_transactions': 'हाल के लेनदेन',
      'to_mobile': 'मोबाइल को',
      'people': 'लोग',
      'view_all': 'सभी देखें',
      'setup': 'सेटअप',
      'offers_rewards': 'ऑफ़र और पुरस्कार',
      'autopay_management': 'ऑटोपे प्रबंधन',
      'chatbot': 'एक्सपेंस्या',
    },
    'te': {
      'my_money': 'నా డబ్బు',
      'payment_settings': 'చెల్లింపు సెట్టింగ్‌లు',
      'app_settings': 'యాప్ సెట్టింగ్‌లు',
      'more': 'మరిన్ని',
      'language': 'భాష',
      'theme': 'థీమ్',
      'notifications': 'నోటిఫికేషన్లు',
      'privacy_security': 'గోప్యత & భద్రత',
      'help_support': 'సహాయం & మద్దతు',
      'about': 'గురించి',
      'logout': 'లాగ్ అవుట్',
      'bank_accounts': 'బ్యాంక్ ఖాతాలు',
      'my_cards': 'నా కార్డులు',
      'personal_info': 'వ్యక్తిగత సమాచారం',
      'select_language': 'భాషను ఎంచుకోండి',
      'language_set_to': 'భాష దీనికి సెట్ చేయబడింది: ',
      'home': 'హోమ్',
      'insights': 'అంతర్దృష్టులు',
      'history': 'చరిత్ర',
      'transfer_money': 'డబ్బు బదిలి',
      'to_contact': 'కాంటాక్ట్ కి',
      'to_bank': 'బ్యాంక్ కి',
      'to_self': 'సొంతంగా',
      'check_balance': 'బ్యాలెన్స్',
      'recharge_pay_bills': 'రీఛార్జ్ & బిల్లులు',
      'recent_transactions': 'ఇటీవలి లావాదేవీలు',
      'to_mobile': 'మొబైల్ కి',
      'people': 'ప్రజలు',
      'view_all': 'అన్నీ చూడు',
      'setup': 'సెటప్',
      'offers_rewards': 'ఆఫర్లు & రివార్డులు',
      'autopay_management': 'ఆటోపే మేనేజ్‌మెంట్',
      'chatbot': 'ఎక్స్‌పెన్స్య',
    },
    'ta': {
      'my_money': 'எனது பணம்',
      'payment_settings': 'கட்டண அமைப்புகள்',
      'app_settings': 'பயன்பாட்டு அமைப்புகள்',
      'more': 'மேலும்',
      'language': 'மொழி',
      'theme': 'தீம்',
      'notifications': 'அறிவிப்புகள்',
      'privacy_security': 'தனியுரிமை மற்றும் பாதுகாப்பு',
      'help_support': 'உதவி மற்றும் ஆதரவு',
      'about': 'பற்றி',
      'logout': 'வெளியேறு',
      'bank_accounts': 'வங்கி கணக்குகள்',
      'my_cards': 'எனது கார்டுகள்',
      'personal_info': 'தனிப்பட்ட தகவல்',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'language_set_to': 'மொழி அமைக்கப்பட்டுள்ளது: ',
      'home': 'முகப்பு',
      'insights': 'புலனாய்வு',
      'history': 'வரலாறு',
      'transfer_money': 'பணம் அனுப்பുക',
      'to_contact': 'தொடர்புக்கு',
      'to_bank': 'வங்கிக்கு',
      'to_self': 'சுய கணக்கு',
      'check_balance': 'இருப்பு சரிபார்',
      'recharge_pay_bills': 'ரீசார்ஜ் & பில்கள்',
      'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
      'to_mobile': 'மொபைலுக்கு',
      'people': 'மக்கள்',
      'view_all': 'அனைத்தையும் பார்',
      'setup': 'அமைப்பு',
      'offers_rewards': 'சலுகைகள் மற்றும் வெகுமதிகள்',
      'autopay_management': 'ஆட்டோபே மேலாண்மை',
      'chatbot': 'எக்ஸ்பென்ஸியா',
    },
    'kn': {
      'my_money': 'ನನ್ನ ಹಣ',
      'payment_settings': 'ಪಾವತಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'app_settings': 'ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'more': 'ಇನ್ನಷ್ಟು',
      'language': 'ಭಾಷೆ',
      'theme': 'ಥೀಮ್',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'privacy_security': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
      'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'about': 'ಬಗ್ಗೆ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'bank_accounts': 'ಬ್ಯಾಂಕ್ ಖಾತೆಗಳು',
      'my_cards': 'ನನ್ನ ಕಾರ್ಡ್‌ಗಳು',
      'personal_info': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'language_set_to': 'ಭಾಷೆಯನ್ನು ಇದಕ್ಕೆ ಹೊಂದಿಸಲಾಗಿದೆ: ',
      'home': 'ಹೋಮ್',
      'insights': 'ಒಳನೋಟಗಳು',
      'history': 'ಇತಿಹಾಸ',
      'transfer_money': 'ಹಣ ವರ್ಗಾವಣೆ',
      'to_contact': 'ಸಂಪರ್ಕಕ್ಕೆ',
      'to_bank': 'ಬ್ಯಾಂಕಿಗೆ',
      'to_self': 'ಸ್ವಂತ ಖಾತೆಗೆ',
      'check_balance': 'ಬ್ಯಾಲೆನ್ಸ್ ಚೆಕ್',
      'recharge_pay_bills': 'ರೀಚಾರ್ಜ್ ಮತ್ತು ಬಿಲ್',
      'recent_transactions': 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      'to_mobile': 'ಮೊಬೈಲ್‌ಗೆ',
      'people': 'ಜನರು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'setup': 'ಸೆಟಪ್',
      'offers_rewards': 'ಕೊಡುಗೆಗಳು ಮತ್ತು ಪ್ರತಿಫಲಗಳು',
      'autopay_management': 'ಆಟೋಪೇ ನಿರ್ವಹಣೆ',
      'chatbot': 'ಎಕ್ಸ್‌ಪೆನ್ಸ್ಯ',
    },
  };

  static String s(String key) {
    final code = LocaleManager().locale.value.languageCode;
    return _localizedValues[code]?[key] ?? _localizedValues['en']![key]!;
  }
}
